#!/bin/bash
set -bueo pipefail
IFS=$'\t\n'
export YASOTO_RANDOMIZE_PRCT=3
export YASOTO_SMOOTHING_IN_PRCT=1
export YASOTO_SMOOTHING_OUT_PRCT=2
sadi1="/home/stef/Samples-cleaned/"
sadi2="/home/stef/Samples-OK/StrangerLoops"
rafi () { find "${1}" -regextype egrep -iregex ".*${2}.*" -print | shuf -n1; }
i=0
while true; do
    ./yasoto "$(rafi "${sadi1}" "kick")"         153 3 0 'vol .21 overdrive 10 sinc 10-2000'                  '1,0,7'               '.25,0,4'           '1,.5,15'                       '.25,0,2'             &
    ./yasoto "$(rafi "${sadi1}" "bass")"         153 3 0 'vol .1  overdrive 13  sinc 40-1500'                 '1,.5,8,'              '.75,.5,2'         '1,0,10'                        '.5,.5,2'             &
    ./yasoto "$(rafi "${sadi1}" "(hh|hat)")"     153 3 0 'vol .13 overdrive 5 sinc 5000-20k'                  '1,.5,6'              '1,.5,6'            '.25,.5,6,fuck one two three'    '.5,.5,1'            &
    ./yasoto "$(rafi "${sadi1}" "snare")"        153 2 0 'vol .25 sinc 800-6000 overdrive 14 reverb 20 25'    '2,1,6'               '4,1,2,foo bar'     '.5,3,4'                          '2,1,6,rise 42'     &
    ./yasoto "$(rafi "${sadi1}" "(tom|rim)")"    153 4 0 'vol .2'                                             '3,1,3,rise shit'     '3,1,3,rise'                                                              &
    ./yasoto "$(rafi "${sadi1}" "(worker)")"     153 4 0 'vol .2  reverse reverb 80 50'                       '3,.666,2'            '6,0,2,rise 0'      '3,.666,2'                                            &
    ./yasoto "$(rafi "${sadi1}" "(attack)")"     153 4 0 'vol .1  echos 0.8 0.6 300 0.8'                      '5,.5,1'              '5,.5,1,shit'                                                             &
    ./yasoto "$(rafi "${sadi1}" "(build)")"      153 4 0 'vol .1  echos 0.8 0.6 600 0.6'                      '5,.5,1'              '5,.5,1,'                                                                 &
    ./yasoto "$(rafi "${sadi2}" "")"             153 8 0 'vol .12 reverb 20 15 overdrive 5 50'                '3,0,1'               '.75,.25,2'         '5,0,1'                                               &
    wait -f

echo "##### $(date) [$((++i))] #########" >&2

done

