#!/bin/bash
set -bueo pipefail
IFS=$'\t\n'
rr () { tr -cd "${1:-0-9}" < /dev/urandom > >(head -c"${2:-1}") || true; }
export YASOTO_RANDOMIZE_PRCT=3
export YASOTO_SMOOTHING_IN_PRCT=3
export YASOTO_SMOOTHING_OUT_PRCT=5
export YASOTO_CREATE_REPLAY_FILE=false
sadi="/home/stef/Samples-sorted"

rafi () { find "${1}" -type f -regextype egrep -iregex ".*${2}.*" -print | shuf -n1; }

i=0
while [[ $((i++)) -lt 2 ]]; do
   :
done

wait -f
