#!/bin/bash
set -bueo pipefail
IFS=$'\t\n'
rr () { tr -cd "${1:-0-9}" < /dev/urandom > >(head -c"${2:-1}") || true; }
export YASOTO_RANDOMIZE_PRCT=3
export YASOTO_SMOOTHING_IN_PRCT=3
export YASOTO_SMOOTHING_OUT_PRCT=5
export YASOTO_CREATE_REPLAY_FILE=true
sadi1="/home/stef/Samples-cleaned/"
sadi2="/home/stef/Samples-OK/StrangerLoops"
rafi () { find "${1}" -type f -regextype egrep -iregex ".*${2}.*" -print | shuf -n1; }
i=0
while [[ $((i++)) -lt 2 ]]; do
   echo "##### $(date) [${i} - 1] #########" >&2
  ./yasoto "$(rafi "${sadi1}" "kick")"            154 8  0 "vol .07 overdrive $(rr 5-7) sinc 10-2000"                "1,0,7"    ".25,0,2,pitch 200"     "1,.5,15"     ".25,0,4,rise $(rr 1-9 2)00"    &
  ./yasoto "$(rafi "${sadi1}" "bass")"            154 8  0 "vol .06 overdrive 13  sinc 40-1500"              "1,.5,8,"            ".75,.5,2"          "1,0,10,rise -800"   ".5,.5,2"            &
  ./yasoto "$(rafi "${sadi1}" "(hh|hat)")"        154 8  0 "vol .10 overdrive $(rr 5-9) sinc 5000-20k"                "1,.5,6"              "1,.5,3"            ".25,.5,12,rise 2400"   ".5,.5,1"        &
  ./yasoto "$(rafi "${sadi1}" "snare")"           154 5  0 "vol .10 sinc 800-6000 overdrive 14 reverb 20 25"  "2,1,6"           "4,0,2,pitch -200"     ".25,.75,2" "2,0,6,rise $(rr 2-7)00"  &
  ./yasoto "$(rafi "${sadi1}" "(tom|rim)")"       154 11 0 "vol .12"                                          "3,1,3,rise 50"      "3,1,3,rise -50"       &
  ./yasoto "$(rafi "${sadi1}" "(worker)")"        154  9 0 "vol .20 reverse reverb $(rr 2-8)0 50"             "3,.666,2"            "6,0,2,rise $(rr 1-5)00"   "3,.666,2"     &
  ./yasoto "$(rafi "${sadi1}" "(attack)")"        154 11 0 "vol .12 echos 0.$(rr 789) 0.6 300 0.8"            "5,.5,1"              "5,.5,1,pitch $(rr 5-9)00"    &
  ./yasoto "$(rafi "${sadi1}" "(build|select)")"  154 11 0 "vol .12 echos 0.8 0.6 600 0.$(rr 3-7)"                    "5,.5,1"              "5,.5,1,"                   &
  ./yasoto "$(rafi "${sadi2}" "")"                154 23 0 "vol .12 reverb 20 15 overdrive 5 $(rr 1-3)0"      "3,0,1,pitch 200"    ".75,.25,2"         "5,0,1,rise 360" &
  wait -n -f;wait -n -f;wait -n -f;wait -n -f;wait -n -f;wait -n -f;wait -n -f; wait -n -f
   echo "##### $(date) [${i} - 2] #########" >&2
  ./yasoto "$(rafi "${sadi1}" "kick")"         154 8  0 "vol .07 overdrive $(rr 5-7) sinc 10-$(rr 1-9)000"         "1,0,7"    ".25,0,2,pitch -800"     "1,.5,1$(rr 1-9)"     ".25,0,4,rise 400"  &
  ./yasoto "$(rafi "${sadi1}" "bass")"         154 8  0 "vol .06 overdrive 13  sinc 40-1500"               "1,.5,8,"            ".75,.5,2"          "1,0,10,rise 800"              ".5,.5,2" &
  ./yasoto "$(rafi "${sadi1}" "(hh|hat)")"     154 8  0 "vol .10 overdrive 5 sinc 5000-20k"                 "1,.5,6"              "1,.5,3"            ".25,.5,12,rise -2400"   ".5,.5,1"  &
  ./yasoto "$(rafi "${sadi1}" "snare")"        154 5  0 "vol .10 sinc 800-6000 overdrive 1$(rr 2-7) reverb $(rr 1-9) 25"    "2,1,6"               "4,0,2,pitch 200"     ".25,.75,2" "2,0,6,rise -400"     &
  ./yasoto "$(rafi "${sadi1}" "(tom|rim)")"    154 11 0 "vol .$(rr 12)2"                                           "3,1,3,rise 50"      "3,1,3,rise -50"                         &
  ./yasoto "$(rafi "${sadi1}" "(worker)")"     154  9 0 "vol .20 reverse reverb 80 50"                      "3,.666,2"            "6,0,2,rise 100"      "3,.666,2"                &
  ./yasoto "$(rafi "${sadi1}" "(attack)")"     154 11 0 "vol .12 echos 0.8 0.6 $(rr 1-3)00 0.$(rr 5-9)"       "5,.5,$(rr 1-3)"              "5,.5,1,pitch $(rr 5-9)$(rr 0-9 2)"                    &
  ./yasoto "$(rafi "${sadi1}" "(die|select)")" 154 11 0 "vol .12 echos 0.8 0.6 600 0.6"                     "5,.5,1"              "5,.5,1,"                    &
  ./yasoto "$(rafi "${sadi2}" "")"             154 23 0 "vol .12 reverb 20 15 overdrive 5 50"               "3,0,1,pitch 200"    ".75,.25,2"         "5,0,1,rise $(rr 1-9)$(rr 0-9 2)"      &
  wait -n -f;wait -n -f;wait -n -f;wait -n -f;wait -n -f;wait -n -f;wait -n -f; wait -n -f
done
wait -f
